import type { Metadata } from "next";

import "./globals.css";
import Image from 'next/image';
import { LogginProvider } from "./context/LogginContext";
import { ProgressProvider } from "./context/ProgressContext";
import { Inter, Ubuntu, Poppins } from 'next/font/google'
import { usePathname } from "next/navigation";
import { useEffect } from "react";

const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-ubuntu',
})
const poppins = Poppins({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
})

const inter = Inter({ subsets: ["latin"] ,variable: '--font-inter',});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  useEffect(() => {
    // Scroll to top when route changes
    window.scrollTo(0, 0);
  }, [pathname]);
  return (
    <html lang="en" className={`${ubuntu.variable} ${poppins.variable} ${ubuntu.className}`}>
      <body className={inter.className}>
      <LogginProvider>
        <ProgressProvider>
          {children}
        </ProgressProvider>
      </LogginProvider>
      </body>
    </html>
  );
}
